module.exports = Object.freeze({

    COOKIX_DPOS_NODE_DEFAULT_EMPTY_STR: '',

    COOKIX_DPOS_NODE_DEFAULT_BLANK_STR: ' ',

    COOKIX_DPOS_NODE_DEFAULT_JSON_PATH: process.env.RPC_PATH || '/',

    COOKIX_DPOS_NODE_DEFAULT_BOOLEAN_TRUE: true,

    COOKIX_DPOS_NODE_DEFAULT_BOOLEAN_FALSE: false,

    COOKIX_DPOS_NODE_DEFAULT_NUM_ONE: 1,

    COOKIX_DPOS_NODE_DEFAULT_PAGE_SIZE: -1,

    COOKIX_DPOS_NODE_DEFAULT_NUM_ZERO: 0,

    COOKIX_DPOS_NODE_DEFAULT_NULL_OBEJCT: null,

    COOKIX_DPOS_NODE_DEFAULT_RATE_BASE: 100,

    COOKIX_DPOS_NODE_DEFAULT_EXCLUDE_SPECIAL_ADDRESSES: [
        '8K9gkit8NPM5bD84wJuE5n7tS9Rdski5uB',
        '8cTn9JAGXfqGgu8kVUaPBJXrhSjoJR9ymG',
        '8S7jTjYjqBhJpS9DxaZEbBLfAhvvyGypKx',
        '8KNrJAyF4M67HT5tma7ZE4Rx9N9YzaUbtM',
        '8VYXVxKKSAxkmRrfmGpQR2Kc66XhG6m3ta',
        '8ZZLWQUDSbjWUn8sEdxEFJsZiRFpzg53rJ',
        '8Pdv2cnsRd7UEHkMg82r85ARQL5CC1S9hG',
        'ELANULLXXXXXXXXXXXXXXXXXXXXXYvs3rr'
    ]

});